version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./web/www:/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - www-network
    php:
        image: php:fpm
        volumes:
            - ./web/www:/www
        networks:
            - www-network

networks:
    www-network:
        driver: bridge
